name: Build YASK USB WiFi
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          git clone --recursive --depth=1 --branch builder https://github.com/topnotchfreaks/kernel_msm-5.15.git kernel
          repo init -u https://android.googlesource.com/kernel/manifest -b common-android13-5.15-lts --depth=1
          repo sync -j8 --no-tags
          rm -rf .repo common
          curl -L https://github.com/topnotchfreaks/clang/releases/download/v1.0.0/clang-r547379.tar.gz -o clang.tar.gz
          mkdir -p prebuilts/clang/host/linux-x86/clang-r547379
          tar -xzf clang.tar.gz -C prebuilts/clang/host/linux-x86/clang-r547379
          rm clang.tar.gz
          cd kernel
          echo 'CONFIG_MT7601U=y' >> arch/arm64/configs/gki_defconfig
          echo 'CONFIG_RT2X00=y' >> arch/arm64/configs/gki_defconfig
          echo 'CONFIG_RT2800USB=y' >> arch/arm64/configs/gki_defconfig
          echo 'CONFIG_RT2800USB_RT33XX=y' >> arch/arm64/configs/gki_defconfig
          echo 'CONFIG_RT2800USB_RT35XX=y' >> arch/arm64/configs/gki_defconfig
          echo 'CONFIG_RT2800USB_RT53XX=y' >> arch/arm64/configs/gki_defconfig
          echo 'CONFIG_RT2800USB_RT55XX=y' >> arch/arm64/configs/gki_defconfig
          ./build/build.sh -j$(nproc)
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: YASK-USB-WiFi
          path: kernel/out/dist/*.zip
